### ISSUE TITLE
Swift 2 Support

### ISSUE THREAD

**Issue by JrGoodle** [modocache/Gift#28]
I started playing around with updating Gift for Swift 2, and was wondering if there has been any work towards this elsewhere? I don't see any branches for it.

One question that I have is what the best course of action would be with regards to error handling. It appears that LlamaKit has been subsumed into the Result project, but Swift 2 also has native error handling capabilities now. Is the Result approach with an Either type preferred, or Swift's own native error handling going forward?

I'd be willing to put some work into this, but don't want to head down a path that isn't the preferred approach.

**Comment by JrGoodle** [comment]
@modocache I'm also wondering how you see the Gift project in relation to [SwiftGit2](https://github.com/SwiftGit2/SwiftGit2). Neither project supports Swift 2 yet, so I'm trying to decide which would be better to put some time into.

**Comment by modocache** [comment]
@JrGoodle Sorry for the delay in responding! SwiftGit2 is definitely the better option.
